# Generated by Django 6.0.4 on 2026-04-16 16:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muon_sach', '0001_initial'),
        ('quan_ly_nguoi_dung', '0001_initial'),
        ('quan_ly_sach', '0001_initial'),
        ('quan_ly_tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinhSachPhat',
            fields=[
                ('ma_loai_phat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('loai_phat', models.CharField(max_length=100)),
                ('muc_phat_moi_ngay', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('muc_phat_hu_hong', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('muc_den_bu_mat_sach', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Chính sách phạt',
                'verbose_name_plural': 'Chính sách phạt',
                'db_table': 'ChinhSachPhat',
                'ordering': ['loai_phat'],
            },
        ),
        migrations.CreateModel(
            name='GiaoDichThanhToan',
            fields=[
                ('ma_giao_dich', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tong_so_tien', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('phuong_thuc', models.CharField(blank=True, max_length=50, null=True)),
                ('thoi_gian_thanh_toan', models.DateTimeField(default=django.utils.timezone.now)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giao_dich_thanh_toan', to='quan_ly_nguoi_dung.nguoidung')),
                ('nguoi_thu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giao_dich_da_thu', to='quan_ly_tai_khoan.taikhoan')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
                'db_table': 'GiaoDichThanhToan',
                'ordering': ['-thoi_gian_thanh_toan'],
            },
        ),
        migrations.CreateModel(
            name='KhoanPhat',
            fields=[
                ('ma_phat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('trang_thai_tt', models.CharField(max_length=50)),
                ('ly_do', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_loai_phat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='tra_sach.chinhsachphat')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='quan_ly_nguoi_dung.nguoidung')),
                ('ma_phieu_muon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='muon_sach.phieumuon')),
                ('ma_sach_trong_kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='quan_ly_sach.sachtrongkho')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat_da_tao', to='quan_ly_tai_khoan.taikhoan')),
            ],
            options={
                'verbose_name': 'Khoản phạt',
                'verbose_name_plural': 'Khoản phạt',
                'db_table': 'KhoanPhat',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_thanh_toan', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('ma_giao_dich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thanh_toan', to='tra_sach.giaodichthanhtoan')),
                ('ma_phat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thanh_toan', to='tra_sach.khoanphat')),
            ],
            options={
                'verbose_name': 'Chi tiết thanh toán',
                'verbose_name_plural': 'Chi tiết thanh toán',
                'db_table': 'ChiTietThanhToan',
                'constraints': [models.UniqueConstraint(fields=('ma_giao_dich', 'ma_phat'), name='unique_chi_tiet_thanh_toan')],
            },
        ),
    ]
