# Generated by Django 6.0.3 on 2026-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muon_sach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieumuon',
            name='trang_thai',
            field=models.CharField(choices=[('dang_muon', 'Đang mượn'), ('qua_han', 'Quá hạn'), ('da_tra', 'Đã trả')], default='dang_muon', max_length=20, verbose_name='Trạng thái mượn'),
        ),
    ]
