# Generated by Django 4.2.8 on 2026-04-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(max_length=255)),
                ('ten_tac_gia', models.CharField(blank=True, max_length=255, null=True)),
                ('the_loai', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_nha_xuat_ban', models.CharField(blank=True, max_length=255, null=True)),
                ('nam_xuat_ban', models.PositiveIntegerField()),
                ('so_luong', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'Sach',
                'ordering': ['ten_sach'],
            },
        ),
        migrations.CreateModel(
            name='SachTrongKho',
            fields=[
                ('ma_sach_trong_kho', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ma_vach', models.CharField(max_length=50, unique=True)),
                ('trang_thai_sach', models.CharField(max_length=50)),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sach_trong_kho', to='quan_ly_sach.sach')),
            ],
            options={
                'verbose_name': 'Sách trong kho',
                'verbose_name_plural': 'Sách trong kho',
                'db_table': 'SachTrongKho',
                'ordering': ['ma_sach_trong_kho'],
            },
        ),
    ]
