# Generated by Django 6.0.3 on 2026-04-18 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_sach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sach',
            options={'verbose_name': 'Sách', 'verbose_name_plural': 'Sách'},
        ),
        migrations.AlterField(
            model_name='sach',
            name='ma_sach',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sachtrongkho',
            name='ma_sach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sach_trong_kho', to='quan_ly_sach.sach'),
        ),
        migrations.AlterField(
            model_name='sachtrongkho',
            name='ma_sach_trong_kho',
            field=models.CharField(editable=False, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sachtrongkho',
            name='ma_vach',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sachtrongkho',
            name='trang_thai_sach',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
