# Generated by Django 6.0.3 on 2026-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_sach', '0002_alter_sach_options_alter_sach_ma_sach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sachtrongkho',
            name='trang_thai_sach',
            field=models.CharField(choices=[('available', 'Có sẵn'), ('borrowed', 'Đang mượn'), ('overdue', 'Quá hạn'), ('awaiting_replacement', 'Chờ đền sách'), ('processed', 'Đã xử lý (Đã đền bù)'), ('damaged', 'Hư hỏng'), ('lost', 'Đã mất')], default='available', max_length=30),
        ),
    ]
