# Generated by Django 4.2.8 on 2026-04-14 04:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChinhSachPhat',
            fields=[
                ('ma_loai_phat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('loai_phat', models.CharField(max_length=100)),
                ('muc_phat_moi_ngay', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('muc_phat_hu_hong', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('muc_den_bu_mat_sach', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'ChinhSachPhat',
                'ordering': ['loai_phat'],
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('ma_nguoi_dung', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('loai_nguoi_dung', models.CharField(max_length=50)),
                ('ho_ten', models.CharField(max_length=255)),
                ('lop', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai_tot_nghiep', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(default='0', max_length=100)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'NguoiDung',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(max_length=255)),
                ('ten_tac_gia', models.CharField(blank=True, max_length=255, null=True)),
                ('the_loai', models.CharField(blank=True, max_length=100, null=True)),
                ('ten_nha_xuat_ban', models.CharField(blank=True, max_length=255, null=True)),
                ('nam_xuat_ban', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Sach',
                'ordering': ['ten_sach'],
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('ma_nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tai_khoan', serialize=False, to='library_system.nguoidung')),
                ('mat_khau', models.CharField(max_length=255)),
                ('vai_tro', models.CharField(max_length=50)),
                ('trang_thai_tai_khoan', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TaiKhoan',
                'ordering': ['ma_nguoi_dung'],
            },
        ),
        migrations.CreateModel(
            name='SachTrongKho',
            fields=[
                ('ma_sach_trong_kho', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ma_vach', models.CharField(max_length=50, unique=True)),
                ('trang_thai_sach', models.CharField(max_length=50)),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sach_trong_kho', to='library_system.sach')),
            ],
            options={
                'db_table': 'SachTrongKho',
                'ordering': ['ma_sach_trong_kho'],
            },
        ),
        migrations.CreateModel(
            name='PhieuMuon',
            fields=[
                ('ma_phieu_muon', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_muon', models.DateField(default=django.utils.timezone.now)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_muon', to='library_system.nguoidung')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_muon_da_tao', to='library_system.nguoidung')),
            ],
            options={
                'db_table': 'PhieuMuon',
                'ordering': ['-ngay_muon'],
            },
        ),
        migrations.CreateModel(
            name='KhoanPhat',
            fields=[
                ('ma_phat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('trang_thai_tt', models.CharField(max_length=50)),
                ('ly_do', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_loai_phat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='library_system.chinhsachphat')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='library_system.nguoidung')),
                ('ma_phieu_muon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='library_system.phieumuon')),
                ('ma_sach_trong_kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat', to='library_system.sachtrongkho')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_phat_da_tao', to='library_system.taikhoan')),
            ],
            options={
                'db_table': 'KhoanPhat',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='GiaoDichThanhToan',
            fields=[
                ('ma_giao_dich', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tong_so_tien', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('phuong_thuc', models.CharField(blank=True, max_length=50, null=True)),
                ('thoi_gian_thanh_toan', models.DateTimeField(default=django.utils.timezone.now)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giao_dich_thanh_toan', to='library_system.nguoidung')),
                ('nguoi_thu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giao_dich_da_thu', to='library_system.taikhoan')),
            ],
            options={
                'db_table': 'GiaoDichThanhToan',
                'ordering': ['-thoi_gian_thanh_toan'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_thanh_toan', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0)])),
                ('ma_giao_dich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thanh_toan', to='library_system.giaodichthanhtoan')),
                ('ma_phat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thanh_toan', to='library_system.khoanphat')),
            ],
            options={
                'db_table': 'ChiTietThanhToan',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuMuon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('han_tra', models.DateField()),
                ('ngay_tra', models.DateField(blank=True, null=True)),
                ('tinh_trang_khi_tra', models.CharField(blank=True, max_length=100, null=True)),
                ('ngay_khai_bao_mat', models.DateField(blank=True, null=True)),
                ('ma_phieu_muon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_phieu_muon', to='library_system.phieumuon')),
                ('ma_sach_trong_kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_phieu_muon', to='library_system.sachtrongkho')),
            ],
            options={
                'db_table': 'ChiTietPhieuMuon',
            },
        ),
        migrations.AddConstraint(
            model_name='chitietthanhtoan',
            constraint=models.UniqueConstraint(fields=('ma_giao_dich', 'ma_phat'), name='unique_chi_tiet_thanh_toan'),
        ),
        migrations.AddConstraint(
            model_name='chitietphieumuon',
            constraint=models.UniqueConstraint(fields=('ma_phieu_muon', 'ma_sach_trong_kho'), name='unique_chi_tiet_phieu_muon'),
        ),
    ]
