# Generated by Django 6.0.3 on 2026-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chinhsachphat',
            options={'ordering': ['loai_phat'], 'verbose_name': 'Chính sách phạt', 'verbose_name_plural': 'Chính sách phạt'},
        ),
        migrations.AlterModelOptions(
            name='chitietphieumuon',
            options={'verbose_name': 'Chi tiết phiếu mượn', 'verbose_name_plural': 'Chi tiết phiếu mượn'},
        ),
        migrations.AlterModelOptions(
            name='chitietthanhtoan',
            options={'verbose_name': 'Chi tiết thanh toán', 'verbose_name_plural': 'Chi tiết thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='giaodichthanhtoan',
            options={'ordering': ['-thoi_gian_thanh_toan'], 'verbose_name': 'Giao dịch thanh toán', 'verbose_name_plural': 'Giao dịch thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='khoanphat',
            options={'ordering': ['-ngay_tao'], 'verbose_name': 'Khoản phạt', 'verbose_name_plural': 'Khoản phạt'},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'ordering': ['ho_ten'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='phieumuon',
            options={'ordering': ['-ngay_muon'], 'verbose_name': 'Phiếu mượn', 'verbose_name_plural': 'Phiếu mượn'},
        ),
        migrations.AlterModelOptions(
            name='sach',
            options={'ordering': ['ten_sach'], 'verbose_name': 'Sách', 'verbose_name_plural': 'Sách'},
        ),
        migrations.AlterModelOptions(
            name='sachtrongkho',
            options={'ordering': ['ma_sach_trong_kho'], 'verbose_name': 'Sách trong kho', 'verbose_name_plural': 'Sách trong kho'},
        ),
        migrations.AlterModelOptions(
            name='taikhoan',
            options={'ordering': ['ma_nguoi_dung'], 'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AddField(
            model_name='sach',
            name='so_luong',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
